server:
  port: 8001

spring:
  application:
    name: cloud-payment-service-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.100.20.166:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: lsh
    password: Lsh123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lyzd.com.lyzd.cloud.pojo    # 所有Entity别名类所在包